Header header
geometry_msgs/Pose pose
geometry_msgs/Twist velocity
geometry_msgs/Twist accel
geometry_msgs/Pose[] end_effectors
geometry_msgs/Twist[] end_effector_velocities
duration max_time
---
Header header
humanoid_catching/FallPoint[] points
float64[] inertia_matrix
float64 body_mass

