Header header
geometry_msgs/Quaternion orientation
geometry_msgs/Twist velocity
humanoid_catching/Link[] end_effectors
humanoid_catching/Link[] links

duration max_time
duration contact_time
duration step_size
duration result_step_size

---
Header header
humanoid_catching/FallPoint[] points
float64[] inertia_matrix
float64 body_mass
float64 radius
float64 height
geometry_msgs/Point ground_contact
